server:
  port: 8080

spring:
  datasource:
    username: user
    password: pass
    url:
      jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    show-sql: false
#logging:
#  level:
#    org.hibernate.SQL: DEBUG
#    org.hibernate.orm.jdbc.bind: TRACE
#    org.hibernate.orm.jdbc.extract: TRACE
#    org.springframework.jdbc.datasource: DEBUG

indexing-settings:
  sites:
#    - url: https://lenta.ru
#      name: Лента.ру
#    - url: https://www.playback.ru
#      name: PlayBack.Ru
    - url: https://ipfran.ru/
      name: Ipfran.Ru
    - url: https://www.svetlovka.ru/
      name: Светловка.Ру
#    - url: https://mpolymer.by
#      name: МПолимер
#    - url: https://constantaclinic.com/
#      name: КонстантаКлиник