server:
  port: 8080
spring:
  profiles:
    active: dev
  datasource:
    username: user
    password: pass
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
#logging:
#  level:
#    org.hibernate.SQL: DEBUG
#    org.hibernate.orm.jdbc.bind: TRACE
#    org.hibernate.orm.jdbc.extract: TRACE
#    org.springframework.jdbc.datasource: DEBUG

jsoup-connect:
  userAgent: Mozilla/5.0 (Windows; U; WindowsNT 5.1; en-US; rv1.8.1.6) Gecko/20070725 Firefox/2.0.0.6
  referrer: http://www.google.com

indexing-settings:
  sites:
    - url: https://lenta.ru
      name: Лента.ру
    - url: https://www.playback.ru
      name: PlayBack.Ru
#    - url: https://ipfran.ru/
#      name: Ipfran.Ru
#    - url: https://www.svetlovka.ru/
#      name: Светловка.Ру
    - url: http://nhghfdkf.ner
      name: Cтремный сайт
